### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [mohamedhassan279/Dots-And-Boxes#1]
Hi. I am starting to learn C programming and found your project while looking for easy simplified examples to learn from. Would you consider adding a permissive license to your project, to allow learning from the code you created, so I (and others) can maybe use similar algorithms to yours in our projects? Your game really looks nice and great to learn from!

**Comment by mohamedhassan279** [comment]
> Hi. I am starting to learn C programming and found your project while looking for easy simplified examples to learn from. Would you consider adding a permissive license to your project, to allow learning from the code you created, so I (and others) can maybe use similar algorithms to yours in our projects? Your game really looks nice and great to learn from!

Thank you for your kind words about my project and for reaching out! I’ve added the GNU General Public License v3.0 (GPL-3.0) to the repository, which ensures the project remains open source and allows others to learn from and use it under the same licensing terms. Feel free to explore the code and use it in your learning journey.

**Comment by LifeCANvs** [comment]
> > Hi. I am starting to learn C programming and found your project while looking for easy simplified examples to learn from. Would you consider adding a permissive license to your project, to allow learning from the code you created, so I (and others) can maybe use similar algorithms to yours in our projects? Your game really looks nice and great to learn from!
> 
> Thank you for your kind words about my project and for reaching out! I’ve added the GNU General Public License v3.0 (GPL-3.0) to the repository, which ensures the project remains open source and allows others to learn from and use it under the same licensing terms. Feel free to explore the code and use it in your learning journey.

Oh, OK. I will then look for other projects to learn from, because as I understand the GPL (or GPhelL), it is not really possible to learn from such licensed code, as you are then placed under the same extreme restrictions with ANY and all code that you write which includes any algorithms or partial code from it, as it is regarded as "derivative work". Also, I can not go along with a license which was created by a person who at the time of creating the license, had the mindset that it should be acceptible for people in positions of greater power than others, to force that power down upon the less powerful person (feel free to research his views and public expression regarding acceptance of predatory behaviour of adults with regards to children). Lastly, it is my view that the GPL is NOT about being open and free, as it does exactly the opposite with its extremely long list of restrictions and requirements forced down upon everyone who interacts with what ever it is applied to. Thanks anyway for your well-meaning response and kind words. It is unfortunate that the lies of the GPL has been so thoroughly marketed and wide spread to condition most people into believing it is actually "for the greater good" and "in the best interest of the community".

**Comment by mohamedhassan279** [comment]
> > > Hi. I am starting to learn C programming and found your project while looking for easy simplified examples to learn from. Would you consider adding a permissive license to your project, to allow learning from the code you created, so I (and others) can maybe use similar algorithms to yours in our projects? Your game really looks nice and great to learn from!
> > 
> > 
> > Thank you for your kind words about my project and for reaching out! I’ve added the GNU General Public License v3.0 (GPL-3.0) to the repository, which ensures the project remains open source and allows others to learn from and use it under the same licensing terms. Feel free to explore the code and use it in your learning journey.
> 
> Oh, OK. I will then look for other projects to learn from, because as I understand the GPL (or GPhelL), it is not really possible to learn from such licensed code, as you are then placed under the same extreme restrictions with ANY and all code that you write which includes any algorithms or partial code from it, as it is regarded as "derivative work". Also, I can not go along with a license which was created by a person who at the time of creating the license, had the mindset that it should be acceptible for people in positions of greater power than others, to force that power down upon the less powerful person (feel free to research his views and public expression regarding acceptance of predatory behaviour of adults with regards to children). Lastly, it is my view that the GPL is NOT about being open and free, as it does exactly the opposite with its extremely long list of restrictions and requirements forced down upon everyone who interacts with what ever it is applied to. Thanks anyway for your well-meaning response and kind words. It is unfortunate that the lies of the GPL has been so thoroughly marketed and wide spread to condition most people into believing it is actually "for the greater good" and "in the best interest of the community".

The GPL does not prevent learning from code. You are free to read, analyze, and even use similar ideas in your projects. However, directly copying or adapting GPL-licensed code does require compliance with its terms. If you write new code inspired by GPL software (without directly copying it), your code isn’t automatically covered by the GPL.

The key issue arises only when GPL code or its derivatives are directly used. The GPL is designed to ensure that software remains free and open for everyone, preventing proprietary forks. While some view this as restrictive, others see it as a safeguard for openness and fairness.

Anyway, good luck with your learning journey.

**Comment by LifeCANvs** [comment]
> > > > Hi. I am starting to learn C programming and found your project while looking for easy simplified examples to learn from. Would you consider adding a permissive license to your project, to allow learning from the code you created, so I (and others) can maybe use similar algorithms to yours in our projects? Your game really looks nice and great to learn from!
> > > 
> > > 
> > > Thank you for your kind words about my project and for reaching out! I’ve added the GNU General Public License v3.0 (GPL-3.0) to the repository, which ensures the project remains open source and allows others to learn from and use it under the same licensing terms. Feel free to explore the code and use it in your learning journey.
> > 
> > 
> > Oh, OK. I will then look for other projects to learn from, because as I understand the GPL (or GPhelL), it is not really possible to learn from such licensed code, as you are then placed under the same extreme restrictions with ANY and all code that you write which includes any algorithms or partial code from it, as it is regarded as "derivative work". Also, I can not go along with a license which was created by a person who at the time of creating the license, had the mindset that it should be acceptible for people in positions of greater power than others, to force that power down upon the less powerful person (feel free to research his views and public expression regarding acceptance of predatory behaviour of adults with regards to children). Lastly, it is my view that the GPL is NOT about being open and free, as it does exactly the opposite with its extremely long list of restrictions and requirements forced down upon everyone who interacts with what ever it is applied to. Thanks anyway for your well-meaning response and kind words. It is unfortunate that the lies of the GPL has been so thoroughly marketed and wide spread to condition most people into believing it is actually "for the greater good" and "in the best interest of the community".
> 
> The GPL does not prevent learning from code. You are free to read, analyze, and even use similar ideas in your projects. However, directly copying or adapting GPL-licensed code does require compliance with its terms. If you write new code inspired by GPL software (without directly copying it), your code isn’t automatically covered by the GPL.
> 
> The key issue arises only when GPL code or its derivatives are directly used. The GPL is designed to ensure that software remains free and open for everyone, preventing proprietary forks. While some view this as restrictive, others see it as a safeguard for openness and fairness.
> 
> Anyway, good luck with your learning journey.

Thanks. Can you point me to where (in that long, complex license of GPL, or elsewhere?) it is clarified that GPL code may legally be analyzed and interpreted and new code created as a result, without it having GPL forced on it? It does however seem from the very extensive legalese in the GPL, that it would be very challenging to have any (even only somewhat) similar code that is created after studying a GPL project's code NOT be regarded as "derivative work" and thus to be free from the shackles of the GPhelL.

As for "GPL is designed to ensure that software remains free and open for everyone, preventing proprietary forks" - you as the creator of the code control 100% whether it remains free and open for everyone. For as long as the original project exists with a free and open license (which GPL objectively is NOT by its restrictive and controlling nature), then it WILL remain truly free and open to everyone. It is also amusing how people have a fear of commercial forks... Take FreeBSD as an example of how beneficial it can be if big companies actually find your code useful and decide to use it, as it is well known that the companies that make most use of FreeBSD code (Sony, Netflix, Apple), are most definitely contributing back to the FreeBSD project, as it is in their best interest to keep it going and evolving and improving...

If I "release" something as "free and open", but I attach a list of requirements and restrictions that is 10s of pages long, is it really free and open?

Ironically GPL also PREVENTS any specific requirements or restrictions to be added to such licensed code - even if it is for GOOD purposes. E.g. if I want to prevent any modifications that I made to your code from being used for any evil or harmful purposes or in any such contexts (e.g. military or criminal activities), I can NOT add any such clause to the GPL, as it does not allow any usage conditions to be added, regardless of how well intended or positive they may be.

Thanks again, and good luck with your project.
